### ISSUE TITLE
Debuffs that I can remove from the group are not displayed

### ISSUE THREAD

**Issue by antoxa-kms** [AzeriteTeam/AzeriteUI#10]
### Make sure you can check all these boxes  
- [+ ] I have the latest addon version available from CurseForge/Twitch.
- [+ ] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [+ ] Yes
- [ ] No

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [+ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Expected behaviour  
Displays debuffs on a group that I can remove ..

### Actual behaviour  
The group does not display icons, the debuff of which I could remove ..

**Comment by goldpaw** [comment]
Can anyone verify if this is still happening or not? Dispellable debuffs SHOULD be there, on a single button in the middle of the group frames.

**Comment by goldpaw** [comment]
Closing this as it's been quite some time since I asked the last question. Consider it solved or a non-issue.
