### ISSUE TITLE
some improvements

### ISSUE THREAD

**Issue by Ksaelan** [AzeriteTeam/AzeriteUI#13]
1. It`s impossible to use all of character`s abilities, mounts, trinkets and other usefull stuff like HS, having only 24 action buttons. You need minimum 36 not counting 24 more on the right panel. So please, add at least extra 12.
2. A very important part of the game is interacting with your inventory, but there`s no button for it. Pressing Shift+B every time is not an option, and i think there`s a perfect place for inventory button in main menu right below character info.
3. Interface appears only if I target something. Dunno if this is a bug or a feature, but I think we all need a permanently visible interface option working correctly.

*Sorry for my english, mates)

**Comment by goldpaw** [comment]
1. We think 24 is enough. We never intended for this UI to be for everybody, or to replicate everything in the default UI. Simplicity and a less complicated gameplay style is what we're aiming for. Macros and modifier keys can make those 24 buttons go quite far! We do support bartender for those that need more buttons, though. And you can use our Azerite masque skin to get an approximate look:  https://www.curseforge.com/wow/addons/masque-azerite

2. Middle-click the mouse wheel button on the cogwheel icon in the bottom right corner to open the bags. It's there, we just haven't really told anyone about it. My bad! I'm working on a better description (with pictures) for the download pages, it's truly needed! :o 

3. All the fading can be disabled! Cogwheel menu right click -> Explorer Mode. That's the setting to toggle whether or not the interface fades in/out depending on the situation. And also Cogwheel menu right click -> ActionBars -> Extra buttons visibility to decide if buttons 8-24 should fade or not. 

Having all that said, a pet bar and a stance bar is coming, that should make things a lot easier for a lot of classes, and free up some button slots too.

**Comment by Feichtmeier** [comment]
> Having all that said, a pet bar and a stance bar is coming, that should make things a lot easier for a lot of classes, and free up some button slots too.

I'm really looking forward to this, is this coming this year? Best regards
