### ISSUE TITLE
"Ease Addon Controller" support

### ISSUE THREAD

**Issue by qazomardok** [AzeriteTeam/AzeriteUI#15]
### Make sure you can check all these boxes  
- [+] I have the latest addon version available from CurseForge/Twitch.
- [+] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [+] No

### What classes does it happen on?  

- [+] Shaman 

### Steps to reproduce  

Installing addon "Ease Addon Controller"

### Expected behaviour  

Button support

### Actual behaviour  

![Аннотация 2019-04-22 022714](https://user-images.githubusercontent.com/1916649/56476817-33ec8c80-64a6-11e9-8f29-e1939dd72956.jpg)

**Comment by goldpaw** [comment]
Ease Addon Controller fires off multiple bugs at startup, and it hasn't been updated in over 2 years since the middle of the Legion expansion back in early 2017:
https://wow.curseforge.com/projects/easeaddoncontroller/files

I'm not going to add support for an addon that is both bugged and outdated.

**Comment by goldpaw** [comment]
I recommend Addon Control Panel (ACP) instead. It's at least updated for BFA, and works flawlessly with the UI: 
https://www.curseforge.com/wow/addons/acp

![Screenshot from 2019-04-22 11-44-38](https://user-images.githubusercontent.com/6476535/56494894-24943000-64f4-11e9-9919-ef5ae4061fb0.png)

![Screenshot from 2019-04-22 11-44-34](https://user-images.githubusercontent.com/6476535/56494899-265df380-64f4-11e9-8482-d9ce4ecce376.png)
