### ISSUE TITLE
Cooldown "Unstable Affliction" of the Warlock is not displayed on target. Version 1.2.140

### ISSUE THREAD

**Issue by Paramendum** [AzeriteTeam/AzeriteUI#16]
Hi.

As described above, various cooldowns of my own spells are missing from the target display. In this case unstable affliction of the warlock. This spell must be held at cooldown. I'm using version 1.2.140 of Azerite UI.

**Comment by Paramendum** [comment]
The Deathknights ability / aura cooldown of "Frozen run weapon" is not displayed on the target either.

**Comment by Paramendum** [comment]
The Deathknights ability / aura cooldown of "Frozen run weapon" is not displayed on the target either.

**Comment by goldpaw** [comment]
Any class, spec or talent spells should've been there, so it's probably an oversight and/or missing entry in our whitelists. I'll fix this in the upcoming rewrite of the aura filtering. Going to close this issue, as it'll be covered by what we're talking about in issue #8 now. :)
