### ISSUE TITLE
Fury Warrior Buffs Not Shown

### ISSUE THREAD

**Issue by Aranzeb** [AzeriteTeam/AzeriteUI#20]
## The problem  
I tried disconnecting then relogging, didn't work, also removing addon and re-installing, didn't work.

### Make sure you can check all these boxes  
- [x ] I have the latest addon version available from CurseForge/Twitch.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [ ] Yes
- [x] No

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [x ] Warrior 

### Any logs, error output, etc?  
No

### Steps to reproduce  
I was playing fury warrior and while i was on a dungeon i notice the buffs weren't showing

### Expected behaviour  

Buffs of debuffs should be able to show on the UI

### Actual behaviour  
Buffs icons weren't showing on the current azeriteUI

**Comment by goldpaw** [comment]
You should see if this is the case both in and out of combat, as the current filter shows short term buffs in combat, long duration / no duration out of combat. 

Apart from that, I'm rewriting the filter to a better priority based one instead, and we have an open ticket about this which covers this issue too already, so I'm marking this one as a duplicate.

I refer to #8

**Comment by Aranzeb** [comment]
Well i do appreciate you taking time and reading my report, i'll wait anxiously for feature aura azeriteUI updates. thank you for such an awesome UI. Looking forward for those auras.
