### ISSUE TITLE
Action Bar doesn't respond to keybind input

### ISSUE THREAD

**Issue by trevor2019** [AzeriteTeam/AzeriteUI#22]
## The problem  
When I remove AzeriteUI I can reliably engage any action bar with my MMO mouse using keybind keys.

### Make sure you can check all these boxes  
- [X] I have the latest addon version available from CurseForge/Twitch.
- [X] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  
- [X] No

### What classes does it happen on?  
I play all classes and have felt this issue across them.

### Any logs, error output, etc?  
No logs that I'm aware of

### Steps to reproduce  
Enter combat
Press action bar keybind input repeatedly
Action is available but not responding until I click with mouse button manually

### Expected behaviour  
Action bar responds to keybind input all the time

### Actual behaviour  
Action bar doesn't respond with keybind input

**Comment by trevor2019** [comment]
I received a random LUA while trying to cast spells in a BG:

Message: ...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:522: script ran too long
Time: Sun Jun 23 20:57:23 2019
Count: 3
Stack: ...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:522: script ran too long
...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:522: in function `Update'
...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:346: in function `?'
...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:966: in function <...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:962>

Locals: self = AzeriteUIActionButton9 {
 0 = <userdata>
 Point = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:216
 SetHeight = <function> defined =[C]:-1
 Border = <unnamed> {
 }
 Flash = <unnamed> {
 }
 CreateStatusBar = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\statusbar.lua:821
 PostUpdateCount = <function> defined @Interface\AddOns\AzeriteUI\front-end\stylesheet.lua:258
 _owner = <unnamed> {
 }
 CreateFrame = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:256
 BorderFrame = <unnamed> {
 }
 rangeTimer = 0.120000
 Overlay = <unnamed> {
 }
 cooldownTimer = 0.010000
 Slot = <unnamed> {
 }
 flashTime = 0.376819
 PostUpdateChargeCooldown = <function> defined @Interface\AddOns\AzeriteUI\front-end\custom\actionbars.lua:688
 _pager = <unnamed> {
 }
 bindingAction = "ACTIONBUTTON5"
 UpdateMouseOver = <function> defined @Interface\AddOns\AzeriteUI\front-end\custom\actionbars.lua:453
 Darken = <unnamed> {
 }
 CreateOrb = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\orb.lua:503
 Backdrop = <unnamed> {
 }
 GetBindingTextAbbreviated = <function> defined @Interface\AddOns\AzeriteUI\front-end\custom\actionbars.lua:442
 maxDisplayCount = 99
 Cooldown = <unnamed> {
 }
 CreateSpinBar = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\spinbar.lua:869
 colors = <table> {
 }
 Glow = <unnamed> {
 }
 action = 0
 PostEnter = <function> defined @Interface\AddOns\AzeriteUI\front-end\custom\actionbars.lua:478
 Place = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:190
 CreateTexture = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:266
 flashing = 0
 PostCreate = <function> defined @Interface\AddOns\AzeriteUI\front-end\custom\actionbars.lua:490
 UpdateBinding = <function> defined @Interface\AddOns\AzeriteUI\front-end\custom\actionbars.lua:446
 PostLeave = <function> defined @Interface\AddOns\AzeriteUI\front-end\custom\actionbars.lua:482
 SpellAutoCast = <unnamed> {
 }
 PostUpdate = <function> defined @Interface\AddOns\AzeriteUI\front-end\custom\actionbars.lua:486
 SetSize = <function> defined =[C]:-1
 SpellHighlight = <unnamed> {
 }
 Icon = <unnamed> {
 }
 ChargeCooldown = <unnamed> {
 }
 CooldownCount = <unnamed> {
 }
 Pushed = <unnamed> {
 }
 PostUpdateCooldown = <function> defined @Interface\AddOns\AzeriteUI\front-end\custom\actionbars.lua:684
 Keybind = <unnamed> {
 }
 id = 5
 hasAction = true
 CreateFontString = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:261
 buttonAction = 5
 outOfRange = false
 FlyoutBorderShadow = <unnamed> {
 }
 Count = <unnamed> {
 }
 FlyoutBorder = <unnamed> {
 }
 Size = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:236
 FlyoutArrow = <unnamed> {
 }
 IsForbidden = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:248
 SetWidth = <function> defined =[C]:-1
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
 Point = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:216
 Place = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:190
 IsForbidden = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:248
 Size = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:236
}
(*temporary) = 136075
(*temporary) = true
(*temporary) = "scri

**Comment by goldpaw** [comment]
Script running too long are random errors often as a result of a lag spike, or just too much happening in the game world at once. It occurs randomly and generally isn't a bug, it's a weakness in WoW's scripting engine. 

When it comes to the issue of keybinds not responding, this sounds to me like you have a conflict with another addon that grabs the keybinds after AzeriteUI has been loaded. You're not using the main bar in bartender or similar?

**Comment by trevor2019** [comment]
I do use Bartender4 actually. Do you feel that these two action bar addons are colliding? 

I can try without BT and report back if you believe that'd be beneficial.

**Comment by goldpaw** [comment]
Yeah.... you're gonna have some problems testing anything right now if you're on the 8.2.0 patch. The UI is broken currently. Working on fixes for it, but not currently in a usable state. Or, well, the actionbars work. But not much else. 

I'm fairly certain it's a conflict of those two, though. When the UI is working again, just make sure that the primary/default/bar1 is disabled (not just hidden) in bartender. Or it will most likely steal the keybinds.

**Comment by goldpaw** [comment]
Forgot to close this. This has been fixed as far as I'm aware.
