### ISSUE TITLE
Right click doesn't open options menu

### ISSUE THREAD

**Issue by Plavalaguna** [AzeriteTeam/AzeriteUI#23]
## The problem  

When I right click the cogwheel, nothing happens.  Left and middle click work just fine, but I can't pull up the options menu.  Is there another way to pull up the options?

I disabled all other addons and it still happens.

### Make sure you can check all these boxes  
- [x] I have the latest addon version available from CurseForge/Twitch.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [x] Yes
- [ ] No

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [x] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, error output, etc?  

No errors appeared.

### Steps to reproduce  

Just right click the cogwheel - I dont think there are any unique steps here.

### Expected behaviour  

AzeriteUI options menu should appear.

### Actual behaviour  

Nothing appears :(

**Comment by goldpaw** [comment]
Broke in 8.2.0 due to undocumented changes in blizzard's restricted environment. Working on fixing it or possibly rewriting the menu from scratch since that might be a better solution at this point. Will keep this issue updated with any progress!

**Comment by Plavalaguna** [comment]
No problem.  Thanks for the update!  Btw I miss your gUI3/gUI4 mod!

**Comment by goldpaw** [comment]
Fixed in 1.2.152-Release!
