### ISSUE TITLE
useless auras displayed on personal resource display (player nameplate)

### ISSUE THREAD

**Issue by lotheac** [AzeriteTeam/AzeriteUI#28]
In 1.2.154-release quite useless auras started displaying in combat on the personal resource display (nameplate under player character - enabled through Interface/Names). It looks like these are essentially the same auras are are shown on the player frame when out of combat, but these show in combat too.
![WoWScrnShot_070619_150912](https://user-images.githubusercontent.com/167940/60756041-189f1100-a001-11e9-83c5-edd6f90bce6d.jpg)

**Comment by goldpaw** [comment]
Yeah that's not supposed to happen! :o 

Must've messed up the nameplate filter somehow, will take a look at it!

**Comment by goldpaw** [comment]
Fixed in 1.2.156-Release

![Screenshot from 2019-07-06 18-26-01](https://user-images.githubusercontent.com/6476535/60758786-8eb07180-a01b-11e9-8d08-d9b3911b51d2.png)
