### ISSUE TITLE
feature request: add interrupted cast indication to nameplates

### ISSUE THREAD

**Issue by lotheac** [AzeriteTeam/AzeriteUI#32]
In the default UI, when casts are interrupted, the cast bars below nameplates will show "Interrupted". However in AzeriteUI the bars just disappear, making an interrupt at the very end of the cast indistinguishable from a finished cast. I think some kind of visual indication for interrupted casts would be nice, as whether or not an enemy finished a cast can be an important factor in deciding what to do next.

**Comment by goldpaw** [comment]
Good idea. Not sure how blizzard does it, but we're talking about basically blanking out the cast bar, writing "interrupted" on it, and leaving it there for half a second or so, right? 

Absolutely a good indicator that's needed in both PvP and some PvE encounters even.

**Comment by lotheac** [comment]
On Sun, Jul 07 2019 09:12:16 -0700, Lars Norberg wrote:
> Good idea. Not sure how blizzard does it, but we're talking about basically blanking out the cast bar, writing "interrupted" on it, and leaving it there for half a second or so, right? 

yep, that is how it appears in default UI.

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by goldpaw** [comment]
Added in 1.2.159-Release for both failed and interrupted casts. Added it to the standard floating castbar as well.
