### ISSUE TITLE
feature request: show absorb on nameplates

### ISSUE THREAD

**Issue by lotheac** [AzeriteTeam/AzeriteUI#33]
Often, enemies gain absorb shields that have some associated mechanics (eg. may be dispellable, or will trigger something when depleted). A good example of this are the Minions of Zul in Kings' Rest: they have 1 hit point, but an absorb shield worth their entire hp pool on top. It is immediately obvious with the default nameplates that something is special about these, but with AzeriteUI they just look like regular almost dead enemies. It'd be nice to add an absorb indicator to nameplates as well (player frame and target frame already seem to have this).

**Comment by goldpaw** [comment]
Accepted!

**Comment by goldpaw** [comment]
Added in 1.2.162-Release.
