### ISSUE TITLE
do not hide targettarget frame when target is a player

### ISSUE THREAD

**Issue by lotheac** [AzeriteTeam/AzeriteUI#38]
By default AzeriteUI hides the targettarget frame if targettarget is player. This is probably reasonable in PvE, as monsters are generally quite predictable and you can tell from the threat indicators whether you are being targeted anyway; although not necessarily -- fixated monsters and certain spellcasts can cause monsters to target things different than their highest threat unit.

I'll leave it up to you to decide whether not hiding it would also be useful in PvE, but my main point is PvP or more generally interaction with players regardless of hostility: players are most unpredictable and do not have a concept of threat. If the target unit is a player, their target should be shown -- this conveys information such as "that player really did just attack me intentionally", or "that hostile unit is most likely on an attack vector", or "this dude is inspecting me or something".

**Comment by goldpaw** [comment]
We do have indicators for this. 

If a hostile target is targeting you, a red eye appears next to its portrait. If a friendly target is targeting you, a green eye appears. If something is targeting your pet, a blue eye appears.

**Comment by lotheac** [comment]
Oh, I missed those. Thanks.
