### ISSUE TITLE
Feature request: Option for increased brightness on actionbuttons

### ISSUE THREAD

**Issue by goldpaw** [AzeriteTeam/AzeriteUI#41]
We should consider adding an option to brighten up the buttons a bit. For a lot of people playing in the daytime on monitors that might not have the greatest contrast range, it can be really hard to see if a button is disabled or not. 

I'll update this issue thread when I have a feature ready.

**Comment by Feichtmeier** [comment]
((( thanks for this awesome addon )))

I second this. Also the contrast between normal buttons and buttons that have a freecast or blink up for some other reason is too low.

**Comment by goldpaw** [comment]
Icons are brighter in 1.2.175-Release. Closed.

**Comment by Feichtmeier** [comment]
Thank you!!!
