### ISSUE TITLE
Duplicate HP bars at times while questing

### ISSUE THREAD

**Issue by vaindil** [AzeriteTeam/AzeriteUI#42]
## The problem  
I'm questing through the Broken Isles and I'm sometimes getting duplicate HP bars. It happens to both friendlies and enemies. It's either happening to everyone or happening to no one, and I don't know what triggers it to start. The bars are varying distances apart; the distance doesn't correlate with anything I can figure out. It's not my distance to the mob, it's not the mob's size, nothing like that. Screenshots are at the bottom.

### Make sure you can check all these boxes  
- [x] I have the latest addon version available from CurseForge/Twitch.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  
- [x] Yes
- [ ] No

### What classes does it happen on?  
- [ ] Death Knight 
- [ ] Demon Hunter 
- [x] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, error output, etc?  
N/A

### Steps to reproduce  
I don't know what causes it to start, trying to figure it out.

### Expected behaviour  
HP bars should not be duplicated.

### Actual behaviour  
HP bars are duplicated.

![image](https://user-images.githubusercontent.com/771134/61920664-6041fa00-af28-11e9-96b9-4ae85a67d223.png)

![image](https://user-images.githubusercontent.com/771134/61920681-6cc65280-af28-11e9-9148-060ad8cb9d13.png)

![image](https://user-images.githubusercontent.com/771134/61920688-76e85100-af28-11e9-91f9-5b35a3874a24.png)

**Comment by goldpaw** [comment]
I'm aware. Got a fix coming in the next update!

**Comment by vaindil** [comment]
Sorry, just realized I forgot to reply after I saw the update. I haven't seen this issue happen since the update after you posted that comment, so everything looks good. Thank you!

**Comment by goldpaw** [comment]
No reply was needed. I fixed this several updates ago, just forgot to close the issue! I should probably have left a comment when closing it, though. My bad! ;)
