### ISSUE TITLE
Nameplates Issue

### ISSUE THREAD

**Issue by Midoki24** [AzeriteTeam/AzeriteUI#43]
Message: Attempt to access forbidden object from code tainted by an AddOn
Time: Sat Aug 10 06:43:40 2019
Count: 2
Stack: Attempt to access forbidden object from code tainted by an AddOn
[C]: ?
[C]: in function `SetParent'
...e\AddOns\AzeriteUI\back-end\libraries\nameplates.lua:1199: in function <...e\AddOns\AzeriteUI\back-end\libraries\nameplates.lua:1197>
[C]: in function `SetParent'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:241: in function `SetupClassNameplateBars'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:150: in function `OnTargetChanged'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:42>
[C]: ?
[C]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: (*temporary) = ClassNameplateBarWindwalkerMonkFrame {
 0 = <userdata>
 ShowNameplateBar = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:84
 Chi5 = <unnamed> {
 }
 Chi1 = <unnamed> {
 }
 scale = ".75"
 class = "MONK"
 Chi2 = <unnamed> {
 }
 SetParent = <function> defined =[C]:-1
 MatchesSpec = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:48
 UpdatePredictedPowerCost = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:149
 powerToken = "CHI"
 spec = 3
 TurnOff = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:100
 Chi6 = <unnamed> {
 }
 Chi4 = <unnamed> {
 }
 OnShow = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:35
 OnLoad = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar_Monk.lua:3
 Chi3 = <unnamed> {
 }
 UpdatePower = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar_Monk.lua:20
 MatchesClass = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:43
 OnEvent = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:11
 Chi = <table> {
 }
 Setup = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:56
 HideNameplateBar = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:89
 OnSizeChanged = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:39
 UpdateMaxPower = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar_Monk.lua:14
 TurnOn = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:96
 OnOptionsUpdated = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:110
 GetUnit = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:113
}
(*temporary) = <unnamed> {
 0 = <userdata>
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
}

**Comment by Midoki24** [comment]
Second Page of Errors:

Message: Attempt to access forbidden object from code tainted by an AddOn
Time: Sat Aug 10 06:44:45 2019
Count: 52
Stack: Attempt to access forbidden object from code tainted by an AddOn
[C]: ?
[C]: in function `SetParent'
...e\AddOns\AzeriteUI\back-end\libraries\nameplates.lua:1199: in function <...e\AddOns\AzeriteUI\back-end\libraries\nameplates.lua:1197>
[C]: in function `SetParent'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:241: in function `SetupClassNameplateBars'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:96: in function `OnNamePlateAdded'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:51: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:42>

Locals: (*temporary) = ClassNameplateBarWindwalkerMonkFrame {
 0 = <userdata>
 ShowNameplateBar = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:84
 Chi5 = <unnamed> {
 }
 Chi1 = <unnamed> {
 }
 scale = ".75"
 class = "MONK"
 Chi2 = <unnamed> {
 }
 SetParent = <function> defined =[C]:-1
 MatchesSpec = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:48
 UpdatePredictedPowerCost = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:149
 powerToken = "CHI"
 spec = 3
 TurnOff = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:100
 Chi6 = <unnamed> {
 }
 Chi4 = <unnamed> {
 }
 OnShow = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:35
 OnLoad = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar_Monk.lua:3
 Chi3 = <unnamed> {
 }
 UpdatePower = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar_Monk.lua:20
 MatchesClass = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:43
 OnEvent = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:11
 Chi = <table> {
 }
 Setup = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:56
 HideNameplateBar = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:89
 OnSizeChanged = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:39
 UpdateMaxPower = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar_Monk.lua:14
 TurnOn = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:96
 OnOptionsUpdated = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:110
 GetUnit = <function> defined @Interface\AddOns\Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua:113
}
(*temporary) = <unnamed> {
 0 = <userdata>
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
}

**Comment by goldpaw** [comment]
You're not using any other addons modifying nameplates or the class resources on nameplates, are you? Just to verify it's not an incompatibility but and actual bug, I mean. 

This does smell like a result of the Blizzard 8.2.0 anchoring changes, though. 

And this happens on a Monk, right?

**Comment by goldpaw** [comment]
Switched to a safer way to disable class nameplate resources in 1.2.167-Release, so this shouldn't be an issue anymore-
