### ISSUE TITLE
Is there any possibility to have a wlk version?

### ISSUE THREAD

**Issue by CalsRanna** [AzeriteTeam/AzeriteUI#45]
Love the ux so much, and i was wondering if there was a wlk version. Even i want to porting it myself, but i don't know how to do it cause i don't have enough lua usage experience and don't know much about wow api. So, if there was no wlk version plan, how could i start it? THX.

**Comment by goldpaw** [comment]
No plans, and I can't help you on it. You'll have to figure out the old WotLK API yourself. And if you do, please do not redistribute the artwork contained in this addon, as that is against its license. 
https://github.com/AzeriteTeam/AzeriteUI/blob/master/LICENSE.md

**Comment by goldpaw** [comment]
I wouldn't recommend trying, though. There are several things this addon does (with the orbs, the action buttons and various other elements) that simply weren't possible until WoW 8.0.1. Porting it to the 3.x API would not only be exceptionally hard, but also lacking a lot of features, as well as just don't look right.

**Comment by CalsRanna** [comment]
Got it. Just forget classic is based on 7.0 framework. I'll try to do it and don't worry, i'll keep the license. thx any way.

**Comment by goldpaw** [comment]
Actually it's based on the 8.x framework. The classic API is a patch layer they put on top of the normal retail API, so it'll constantly get updated to retail level just with classic changes. That's why I was able to make AzeriteUI for Classic, actually. Wouldn't have done it if they had use the vanilla API.
