### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mathusala** [AzeriteTeam/AzeriteUI#46]
## The problem  
Getting the following error:

3x FrameXML\UIParent.lua:3119: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: DurabilityFrame:SetPoint.
[C]: in function `SetPoint'
FrameXML\UIParent.lua:3119: in function `UIParentManageFramePositions'
FrameXML\UIParent.lua:2368: in function <FrameXML\UIParent.lua:2355>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:3164: in function `UIParent_ManageFramePositions'
FrameXML\MainMenuBar.lua:60: in function `SetPositionForStatusBars'
FrameXML\MainMenuBar.lua:8: in function `OnStatusBarsUpdated'
FrameXML\StatusTrackingManager.lua:181: in function `LayoutBars'
FrameXML\StatusTrackingManager.lua:84: in function `UpdateBarsShown'
FrameXML\StatusTrackingManager.lua:209: in function <FrameXML\StatusTrackingManager.lua:205>

Locals:
(*temporary) = DurabilityFrame {
 0 = <userdata>
 IsShown = <function> defined @AzeriteUI\front-end\blizzard\floaters.lua:474
}
(*temporary) = "TOPRIGHT"
(*temporary) = "MinimapCluster"
(*temporary) = "BOTTOMRIGHT"
(*temporary) = 0
(*temporary) = 0

### Make sure you can check all these boxes  
- [ x] I have the latest addon version available from CurseForge/Twitch.
- [x ] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [ x] Yes
- [ ] No

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [x ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, error output, etc?  

ghostbin.com doesn't resolve for me as a site

### Steps to reproduce  

Seems to happen randomly or when I loot

**Comment by goldpaw** [comment]
Super strange that this has started happening again, just out of the blue. Was a bug on a previous wow patch, I fixed it. Guess it's back. I'll whip out the old workaround.

**Comment by goldpaw** [comment]
Should work in 1.2.177-Release.

**Comment by Mathusala** [comment]
Thank you so much! LOVE the addon!
