### ISSUE TITLE
Please add more action bars, and customization overall

### ISSUE THREAD

**Issue by StolenFrog** [AzeriteTeam/AzeriteUI#5]
This is a beautiful looking ui but I can’t actually use it for raid healing because:

• insufficient player buff tracking
• too few action bars even with extra from bartender (space restrictions due to action bar size)
• no way to scale down action bar size 
• no way to move chat frame
• no way to scale down unit frame size

I love the look of this ui but it currently lacks the customization options to be effective for raid healing.

P.S. sorry if this is not the place to submit feedback, I didn’t really see another place to do so

**Comment by goldpaw** [comment]
We have answered most of this in the addon description both here and on Curse already. 
https://www.curseforge.com/wow/addons/azeriteui

We are working on a better aura tracking system, but apart from that we're not planning any of the other suggested changes. More options and more customization is not a goal.
