### ISSUE TITLE
Businessman in mount

### ISSUE THREAD

**Issue by lzz4971509** [AzeriteTeam/AzeriteUI#6]
my english is very bad.but I want you can know my mean

When I mount Traveler's Tundra Mammoth.The NPC Businessman's plate had a lua error

**Comment by goldpaw** [comment]
I'm not getting any errors with any of the nameplates from the NPCs on my Tundra Mammoth. So I would need to see the Lua error to figure that one out, though chances are it's another addon causing it. 

![Screenshot from 2019-03-24 09-30-15](https://user-images.githubusercontent.com/6476535/54876871-7ffcd080-4e17-11e9-9ece-65da80b0809b.png)
![Screenshot from 2019-03-24 09-30-11](https://user-images.githubusercontent.com/6476535/54876872-80956700-4e17-11e9-9370-eb0ee1fade3a.png)
