### ISSUE TITLE
Kaliel's Tracker and AzeriteUI working together

### ISSUE THREAD

**Issue by ZaViper** [AzeriteTeam/AzeriteUI#9]
Hey guys! Just looking for an update. Several months ago, I think back in November, I posted about a bug in AzeriteUI over at your old website before moving over to Github. It was about AzeriteUI not allowing Kaliel's Tracker to show and operate as normal. I thought it could be because of Explorer Mode because versions of AzeriteUI that came before then allowed AzeriteUI to play well with Kaliel's Tracker. I noticed that you guys changed my post from a minor bug to enhancement. After waiting months hoping to use these two add-ons together, I have been wondering if this was going to be resolved or were you guys planning on creating your own quest tracking experience within AzeriteUI since you guys changed it to enhancement.

**Comment by goldpaw** [comment]
Both, really. I'll take a look at this and see if we can get it sorted. :)

**Comment by goldpaw** [comment]
So a little update here. I started up the game with AzeriteUI and Kaliel's Tracker, and sure, I got that error message on the very first logon (not the following logins or reloads) about a nil comparison in line 171 in Kalie's Tracker. The addon worked fine apart from that, and pretty much flawlessly on /reloads. 

Just to be safe, I added in a switch in AzeriteUI that just turned off all involvement with the quest tracker when Kaliel's Tracker is enabled. Then I started the game again, and still got the error on the first login. Curious as to why, I tried restarting the game WITHOUT AzeriteUI. And still got the bug. And then I did a final test where I restarted the game with ONLY Kaliel's Tracker enabled. And yes.... the startup bug was there. 

So whatever the reason for that startup bug is, it's not AzeriteUI. It's Kaliel's Tracker doing something too early in the first startup process, probably before some blizzard addon is loaded or some data not being fully available to the client yet. There are a few of those. 

Anyway. I'm stilling adding that little switch to the next AzeriteUI update, just in case. But apart from that, the only bugs I could find aren't related to AzeriteUI or any other addon I've made, so I'm closing this ticket. 

![Screenshot (21)](https://user-images.githubusercontent.com/6476535/55666985-9b73cc80-5856-11e9-9ec2-c41d73255b52.png)

![Screenshot (23)](https://user-images.githubusercontent.com/6476535/55667040-83e91380-5857-11e9-820b-b0d8a604852a.png)

**Comment by goldpaw** [comment]
I posted a suggested fix for the issue over at the issue tracker for Kaliel's Tracker at CurseForge: 
https://wow.curseforge.com/projects/kaliels-tracker/issues/353

It's a one-liner fix.

**Comment by ZaViper** [comment]
OMG, thank you so much for this! I thought this whole time it was because of AzeriteUI because I never got an error on my end without AzeriteUI loaded. I'm grateful you took the time to check this out and even forwarded the issue to Kaliel's Tracker and added that switch. I sent you $10 through paypal. Have lunch on me tomorrow. I appreciate this man. :)
